version: '3'
services:
  openalpr:
    container_name: alpr_nodejs
    restart: always
    build: .
    ports:
      - "9091:9091"
    volumes:
      - openalpr:/etc/openalpr
      - ./:/code
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.4.8-focal

    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo_db
    image: mongo-express
    depends_on:
       - mongo
    ports:
       - "8081:8081"
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
volumes:
  dbdata:
  openalpr:
  minio_storage: {}
  rabbitmq_data: {}